# Generated by Django 5.0 on 2025-11-14 12:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('total_points', models.IntegerField(default=0, help_text='Total points for the exam, calculated from questions.')),
                ('duration_minutes', models.IntegerField()),
                ('retake_limit', models.IntegerField(default=1)),
                ('randomize_questions', models.BooleanField(default=False)),
                ('randomize_answers', models.BooleanField(default=False)),
                ('allow_review_before_submit', models.BooleanField(default=True)),
                ('allow_review_after_submit', models.BooleanField(default=True)),
                ('show_answers_after_submit', models.BooleanField(default=False)),
                ('enable_proctoring', models.BooleanField(default=False)),
                ('enable_camera', models.BooleanField(default=False)),
                ('browser_lockdown', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to=settings.AUTH_USER_MODEL)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='accounts.engineeringspecialization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('multiple_select', 'Multiple Select'), ('short_answer', 'Short Answer'), ('essay', 'Essay')], max_length=20)),
                ('points', models.DecimalField(decimal_places=2, max_digits=5)),
                ('explanation', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('order_index', models.IntegerField()),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam')),
            ],
            options={
                'ordering': ['exam', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('difficulty_level', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to=settings.AUTH_USER_MODEL)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='accounts.engineeringspecialization')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_text', models.TextField()),
                ('option_image_url', models.URLField(blank=True)),
                ('is_correct', models.BooleanField()),
                ('partial_credit_points', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('order_index', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exams.question')),
            ],
            options={
                'ordering': ['question', 'order_index'],
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['instructor'], name='exams_exam_instruc_0a0350_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['specialization'], name='exams_exam_special_1ac351_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam'], name='exams_quest_exam_id_50daa5_idx'),
        ),
    ]
