# Generated by Django 5.0 on 2025-11-14 12:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('graded', 'Graded')], default='not_started', max_length=20)),
                ('question_randomization_seed', models.CharField(blank=True, max_length=255)),
                ('time_taken_seconds', models.IntegerField(blank=True, null=True)),
                ('retake_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('answer_options', models.JSONField(blank=True, default=list)),
                ('is_flagged', models.BooleanField(default=False)),
                ('is_answered', models.BooleanField(default=False)),
                ('auto_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('manual_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('instructor_feedback', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='submissions.examassignment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='exams.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('tab_switch', 'Tab Switch'), ('right_click', 'Right Click'), ('devtools_open', 'DevTools Opened'), ('copy_attempt', 'Copy Attempt'), ('paste_attempt', 'Paste Attempt'), ('ip_change', 'IP Address Change'), ('rapid_answers', 'Rapid Answering'), ('answer_modification', 'Answer Modification'), ('multiple_logins', 'Multiple Logins'), ('possible_collusion', 'Possible Collusion')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
                ('instructor_reviewed', models.BooleanField(default=False)),
                ('action_taken', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_activities', to='submissions.examassignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.UUIDField()),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user'], name='submissions_user_id_a07170_idx'), models.Index(fields=['entity_type', 'entity_id'], name='submissions_entity__d94573_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='examassignment',
            index=models.Index(fields=['exam', 'student'], name='submissions_exam_id_7e9465_idx'),
        ),
        migrations.AddIndex(
            model_name='examassignment',
            index=models.Index(fields=['status'], name='submissions_status_8bca68_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examassignment',
            unique_together={('exam', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='studentresponse',
            unique_together={('exam_assignment', 'question')},
        ),
        migrations.AddIndex(
            model_name='suspiciousactivity',
            index=models.Index(fields=['exam_assignment'], name='submissions_exam_as_f4ef01_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciousactivity',
            index=models.Index(fields=['activity_type'], name='submissions_activit_a15e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciousactivity',
            index=models.Index(fields=['severity'], name='submissions_severit_858e3d_idx'),
        ),
    ]
